### ISSUE TITLE
Binning for time spectra

### ISSUE THREAD

**Issue by warr** [Miniball/MiniballSort#3]
Max tells me that he sees spikes in his time spectra, which are
consistent with a binning problem. Looking at the source code, I think
I see why. In src/Histogrammer.cc in Histogrammer::MakeHists, you have
a fixed number of bins (1000) but the range is variable. If this range
isn't divisible by 1000, you get spikes. If I've understood correctly,
the default event window is 3000, so you have a range from -3050 to
+3050, which gives you 6.1 ticks per bin. Attached is a plot, which
shows this in blue and a one-to-one binning of the same events (i.e. 1
bin = 1 tick) for a simulated Gauß peak.

So either you need to set the number of bins to match the number of
ticks, or ensure that the number of ticks is divisible by the number
of bins.

e.g.

#define Range(w,n) ((n)/2*(int)ceil(((w)+50.)*2./(n))) // w = window, n =
#bins

and then
auto h = new TH1I("name", "title", 1000, -Range(win, 1000),
Range(win,1000));
auto h2 = new TH2I("name", "title", 200, -Range(win, 200), Range(win,200),
                   whatever);

where win is the event_window. So if win = 3000, instead of using 1000
bins from -3050 to +3050 with 6.1 ticks per bin, it uses 1000 bins
from -3500 to +3500 with 7 ticks per bin or 200 bins from -3100 to
+3100 with 31 ticks per bin.

**Comment by lpgaff** [comment]
Thanks Nigel. I agree that this is the root cause of the problem. I will update this along the lines you have suggested, but try to make some sensible number of ticks per bin, and those units written in the x-axis title of the figure.
